GET http://localhost:8080/api/posts

####

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "content": "Hello"
}

####

DELETE http://localhost:8080/api/posts/4

####

GET http://localhost:8080/api/posts/3